const data1 = [
  {
    id: 1,
    name: 'KC DESIGNS',
    displayImage: './img/display-img/hqdefault.jpg',
    channelImage: './img/channel-img/kc-designs.jpg',
    info: '71 REALISTIC 3D CHARACTER DESIGN, (REFINEMENT) TEXTURING FULL BODY...',
    duration: '1:39:35',
    views: '21 views',
    date: '10 days ago',
  },
  {
    id: 2,
    name: 'Brain Jotter',
    displayImage: './img/display-img/brain-jotter2.jpg',
    channelImage: './img/channel-img/brain-jotter.jpg',
    info: 'Trapped Souls',
    duration: '22:54',
    views: '366k views',
    date: '2 days ago',
  },
  {
    id: 3,
    name: 'Apollo',
    displayImage: './img/display-img/apollo.webp',
    channelImage: './img/channel-img/apollo.jpg',
    info: 'The System Is Changing Fast',
    duration: '47:41',
    views: '44 views',
    date: '2 days ago',
  },
  {
    id: 4,
    name: 'Golden Hoops ',
    displayImage: './img/display-img/kyrie-irving.webp',
    channelImage: './img/channel-img/golden-hoops.jpg',
    info: 'Kyrie Irving Being the MOST SKILLED PLAYER EVER for 10 Minutes Straight!',
    duration: '10:02',
    views: '826k views',
    date: '9 months ago',
  },
  {
    id: 5,
    name: 'NBA 2021',
    displayImage: './img/display-img/kuroko.webp',
    channelImage: './img/channel-img/nba.jpg',
    info: 'Kagami entered the ZONE to challenge Aomine, Akashi',
    duration: '13:41',
    views: '3.9M views',
    date: '3 years ago',
  },
  {
    id: 6,
    name: 'freeCodeCamp.org',
    displayImage: './img/display-img/freecodecamp.webp',
    channelImage: './img/channel-img/freecodecamp.jpg',
    info: 'Frontend Web Development: In Depth Project Tutorial (HTML, CSS, JAVASCRIPT, REACT)',
    duration: '10:02:10',
    views: '34k views',
    date: '8 hours ago',
  },
];

const data2 = [
  {
    id: 1,
    displayImage: './img/display-img/hq720_2 (3).webp',
    info: 'Fastest way to get shredded at home...',
    views: '1.1M views',
  },
  {
    id: 2,
    displayImage: './img/display-img/hq720_2 (8).webp',
    info: 'Burna Boy Teaches The Afro Moonwalk',
    views: '7.2M views',
  },
  {
    id: 3,
    displayImage: './img/display-img/hq720 (14).webp',
    info: 'Damon to Caroline "No One Cares"...',
    views: '16M views',
  },
  {
    id: 4,
    displayImage: './img/display-img/hq720_2 (7).webp',
    info: 'FIX Your Jump Shots Instantly...',
    views: '663k views',
  },
  {
    id: 5,
    displayImage: './img/display-img/hq720.webp',
    info: 'I Put The Flash In The NBA',
    views: '6.6M views',
  },
  {
    id: 6,
    displayImage: './img/display-img/hq720_2 (5).webp',
    info: 'Unlock Your Back In Seconds',
    views: '17M views',
  },
];

const data3 = [
  {
    id: 1,
    name: 'MrBeast',
    displayImage: './img/display-img/mr-beast.jpg',
    channelImage: './img/channel-img/mr-beast.jpg',
    info: 'I Paid A Real Assassin To Try To Kill Me',
    duration: '12:17',
    views: '63M views',
    date: '6 days ago',
  },
  {
    id: 2,
    name: 'official BRODA SHAGGI',
    displayImage: './img/display-img/hq720 (1)_be96c1.webp',
    channelImage: './img/channel-img/brodashaggi.jpg',
    info: 'WHAT ARE FRIENDS FOR |Brodasghaggi | Shank comics',
    duration: '12:35',
    views: '1.4M views',
    date: '3 months ago',
  },
  {
    id: 3,
    name: 'Ivan Rusakov',
    displayImage: './img/display-img/Ivan-Rusakov.webp',
    channelImage: './img/channel-img/ivan-rusakov.jpg',
    info: 'Just Try This Workout ( 100% Change Your Body)',
    duration: '3:33',
    views: '11M views',
    date: '1 year ago',
  },
  {
    id: 4,
    name: 'MasterClass',
    displayImage: './img/display-img/hq720 (11)_6088a2.webp',
    channelImage: './img/channel-img/nba.jpg',
    info: 'Stephen Curry Teaches Shooting, Ball-Handling and Scoring | official',
    duration: '2:37',
    views: '5.3M views',
    date: '2 years ago',
  },
  {
    id: 5,
    name: 'Ronnie7M',
    displayImage: './img/display-img/hq720 (9)_1f0f78.webp',
    channelImage: './img/channel-img/ronnie7M.jpg',
    info: 'Cristiano Ronaldo 50 Legendary Goals Impossible To Forget',
    duration: '10:33',
    views: '33M views',
    date: '2 years ago',
  },
  {
    id: 6,
    name: 'Aniplot',
    displayImage: './img/display-img/hq720 (10)_95bc50.webp',
    channelImage: './img/channel-img/aniplot.jpg',
    info: 'Poor Boy Accidentally Becomes Heir Of The Strongest Ninja Clan',
    duration: '13:08',
    views: '1.2M views',
    date: '4 weeks ago',
  },
  {
    id: 7,
    name: 'Netflix',
    displayImage: './img/display-img/hq720 (3)_cbd2a1.webp',
    channelImage: './img/channel-img/netflix.jpg',
    info: 'Wednesday Addams | Season 2 Announcement | Netflix',
    duration: '0:56',
    views: '20M views',
    date: '3 months ago',
  },
  {
    id: 8,
    name: 'official BrodaShaggi',
    displayImage: './img/display-img/hq720 (12)_376e01.webp',
    channelImage: './img/channel-img/brodashaggi.jpg',
    info: 'Avengers dey find Super Shaggi, he Dey Mushin Dey cause trouble |...',
    duration: '2:00',
    views: '54k views',
    date: '15 hours ago',
  },
  {
    id: 9,
    name: 'Wave Man Mike',
    displayImage: './img/display-img/hq720 (7)_845d65.webp',
    channelImage: './img/channel-img/waveman-mike.jpg',
    info: 'Afro To Waves (360 Waves Wash and Style)',
    duration: '14:22',
    views: '1.5M views',
    date: '2 years ago',
  },
  {
    id: 10,
    name: 'Golden Hoops',
    displayImage: './img/display-img/hq720 (4)_57da3d.webp',
    channelImage: './img/channel-img/golden-hoops.jpg',
    info: `Ja Morant's Most Atheltic Career Dunks`,
    duration: '10:02',
    views: '81k views',
    date: '2 days ago',
  },
  {
    id: 11,
    name: 'Programming with Mosh',
    displayImage: './img/display-img/hq720 (6)_460917.webp',
    channelImage: './img/channel-img/programming-with-mosh.jpg',
    info: 'HTML Tutorial for Beginners: HTML Crash Course',
    duration: '1:09:34',
    views: '6.1M views',
    date: '2 years ago',
  },
  {
    id: 12,
    name: 'Professor Live',
    displayImage: './img/display-img/hq720 (2)_222d93.webp',
    channelImage: './img/channel-img/professor-live.jpg',
    info: 'Professor CALLED OUT 1v1 vs Florida Trash Talker',
    duration: '16:08',
    views: '7.9M views',
    date: '1 year ago',
  },
];

export { data1, data2, data3 };
